name: CI Java Reusable Workflow (Dry Run)

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      docker-image-name:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      SNYK_TOKEN:
        required: true

jobs:
  code-style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Dry Run - Code Style Check
        run: echo "Running Code Style Check with Java ${{ inputs.java-version }}"

  unit-tests:
    runs-on: ubuntu-latest
    needs: code-style-check
    steps:
      - name: Dry Run - Unit Tests
        run: echo "Running Unit Tests with Java ${{ inputs.java-version }}"

  sonar-scan:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Dry Run - Sonar Scan
        run: echo "Running Sonar Scan with SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}"

  snyk-scan:
    runs-on: ubuntu-latest
    needs: sonar-scan
    steps:
      - name: Dry Run - Snyk Scan
        run: echo "Running Snyk Scan with SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}"

  build-docker:
    runs-on: ubuntu-latest
    needs: [unit-tests, sonar-scan]
    if: always() # allow it to run even if conditions not met
    steps:
      - name: Dry Run - Build Docker Image
        run: echo "Building Docker Image ${{ inputs.docker-image-name }} with commit ${{ github.sha }}"
